### ISSUE TITLE
Error java.lang.NoClassDefFoundError:

### ISSUE THREAD

**Issue by josephkandi** [aimardcr/APKKiller#18]
I have followed the steps and seems am missing something. I copied the com/kuro to the target app smali folder. When I rebuild and re-run the app, I get the following error:
```
Process: com.sample.sample, PID: 9865
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/kuro/APKKIller;
	at com.sample.SampleApp.onCreate(Unknown Source:2)
	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6805)
```

I have the below on the class that extends the Android Application class:
```
.method public onCreate()V
    .locals 10
    sput-object p0, Lkn/ࡨࡱ;->ࡣ:Landroid/content/Context;
    invoke-static {p0}, Lcom/kuro/APKKIller;->Start(Landroid/content/Context;)V
```

My folder structure looks as follows after copying the com/kuro smalli folder:
<img width="482" alt="image" src="https://github.com/aimardcr/APKKiller/assets/3235272/4b4b7a9b-32d8-4871-9161-81d634250caf">

**Comment by Kaspek2480** [comment]
try that:

```
.method protected onCreate(Landroid/os/Bundle;)V
    .locals 0

    invoke-static {p0}, Lcom/kuro/APKKiller;->Start(Landroid/content/Context;)V
```
